import AppNavbar from "@/components/layout/AppNavbar";
import Providers from "@/components/Providers/Providers";
import { ScrollArea } from "@/components/ui/scroll-area";
import type { Metadata } from "next";
import { poppinsFont } from "../fonts";
import "../globals.css";
import { getDesign } from "@/lib/actions/globals.actions";
import { getAppFont } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Apex Intro",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { appFont } = await getDesign();

	return (
		<html lang="en" suppressHydrationWarning>
			<Providers>
				<ScrollArea className="h-[100vh]">
					<body
						// className={`${geistSans.variable} ${geistMono.variable} antialiased p-3`}
						className={` ${getAppFont(appFont).className} antialiased`}
					>
						<AppNavbar className="sticky top-5 z-30" />
						<main className="p-3 overflow-x-hidden max-w-screen">
							{children}
						</main>
					</body>
				</ScrollArea>
			</Providers>
		</html>
	);
}
