import AppNavbar from "@/components/layout/AppNavbar";
import Providers from "@/components/Providers/Providers";
import { ScrollArea } from "@/components/ui/scroll-area";
import { getDesign } from "@/lib/actions/globals.actions";
import { getAppFont } from "@/lib/utils";
import type { Metadata } from "next";
import "../globals.css";
import { LivePreview } from "@/components/layout/LivePreview";

export const metadata: Metadata = {
	title: "Apex Intro",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { appFont } = await getDesign();

	return (
		<html lang="en" suppressHydrationWarning>
			<ScrollArea className="h-[100vh]">
				<body
					className={` ${getAppFont(appFont).className} antialiased relative`}
				>
					<LivePreview />
					<Providers>
						<AppNavbar className="sticky top-5 z-30" />
						<main className="p-3 overflow-x-hidden max-w-screen">
							{children}
						</main>
					</Providers>
				</body>
			</ScrollArea>
		</html>
	);
}
